### ISSUE TITLE
More descriptive description of the design in README

### ISSUE THREAD

**Issue by davelab6** [brandnewtype/hoogli#1]
Please add a description of the design and project to the README that I can use in the www.google.com/fonts directory 'about' text :)

**Comment by naorem** [comment]
Hi Dave,
You want me to revised this description or is this fine?
.....................

Hoogli is a casual, low contrast, rounded bengali typeface developed based on continuous writing style using round nib tool. The large counters and its balanced proportions makes the typeface ideal for easy reading on screen as well as on print. The rounded terminals and the loops gives the typeface a unique personality while creating a distinctive overall texture.

Hoogli is available free on Google Fonts.

....................

**Comment by davelab6** [comment]
This is good :)
